---
language: python

sudo: required
dist: bionic

addons:
  postgresql: '10'
  chrome: stable
  apt:
    update: true
    packages:
      - postgresql-10-postgis-2.5
      - postgresql-10-postgis-2.5-scripts

env:
  global:
    - ES_VERSION=7.5.1 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}-amd64.deb
python:
  - '3.6.9'
  - '3.7.4'

services:
  - postgresql

# before_install:
#   - sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

install:
  - wget https://chromedriver.storage.googleapis.com/$(wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE -q -O -)/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - wget ${ES_DOWNLOAD_URL}
  - sudo dpkg -i --force-confnew elasticsearch-${ES_VERSION}-amd64.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl start elasticsearch
  - pip install -r requirements-test.txt
  - pip install psycopg2-binary coveralls
  - pip install -e .
  - yarn install && yarn run build

before_script:
  - psql -U postgres -c 'create database froide WITH OWNER travis;'
  - psql -U postgres -c 'CREATE EXTENSION postgis;' -d froide
  - psql -U postgres -c 'CREATE EXTENSION postgis_topology;' -d froide
  - psql -U postgres -c "ALTER USER travis WITH PASSWORD 'travis';"
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

script:
  - set -e
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - export CHROME_DRIVER_PATH=/usr/local/bin/chromedriver
  - export DATABASE_URL=postgis://travis:travis@127.0.0.1/froide
  - which google-chrome-stable
  - google-chrome-stable --version
  - which chromedriver
  - chromedriver --version
  - make test
after_success:
  - coveralls
