version: '3'

services:
  db:
    image: mdillon/postgis:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "127.0.0.1:5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-log:/var/log
    ports:
      - "127.0.0.1:9200:9200"

volumes:
  postgres_data: {}
  elasticsearch-data: {}
  elasticsearch-log: {}
